/**
 * @File Name          : teste.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 07/01/2020 12:05:41
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    06/01/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public class teste {
    public String nome;
    public String city;
}